version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Create an empty requirements.txt file
      - run:
          name: Create requirements.txt
          command: touch requirements.txt

      # Install dependencies
      - run: pip install -r requirements.txt  # Include this line if you have any dependencies

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: python -m unittest discover

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main

  test_suite_dev:
    jobs:
      - test:
          filters:
            branches:
              only:
                - test_suite_dev

